[tool.black]
line-length = 100
target-version = ["py310", "py311", "py312", "py313"]

[tool.isort]
profile = "black"
line_length = 100

[tool.ruff]
line-length = 100
select = ["E", "F", "I"]  # pyflakes/pycodestyle/imports
ignore = []

[tool.ruff.lint.isort]
combine-as-imports = true